name: our_video_player
description: "Our video player is only root video player modified version"
version: 0.0.1
repository: https://github.com/Plantake-Corp/our_video_player.git

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter: